// loginradius-js/solid/src/App.tsx
import { onMount } from 'solid-js';
import { LoginRadiusSDK } from '@loginradius/loginradius-js';
import './App.css';

function App() {
  onMount(() => {
    // Check for required environment variables
    const apiKey = import.meta.env.VITE_LOGINRADIUS_API_KEY;
    const sott = import.meta.env.VITE_LOGINRADIUS_SOTT;

    // Initialize LoginRadius SDK
    const loginRadius = new LoginRadiusSDK({
      apiKey,
      sott,
    });

    // Initialize login interface
    loginRadius.init('login', {
      container: 'auth-container',
      onSuccess: (response: unknown) => {
        console.log('Login response:', response);
      },
      onError: (error: { error?: string; errorCode?: number }) => {
        console.error('Login error:', error);
      },
    });
  });

  return (
    <div class="main-container">
      <div id="auth-container"></div>
    </div>
  );
}

export default App;

// loginradius-js/angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { LoginRadiusSDK } from '@loginradius/loginradius-js';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  imports: [],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit {
  ngOnInit() {
    // Initialize LoginRadius SDK
    const loginRadius = new LoginRadiusSDK({
      apiKey: environment.loginradiusApiKey,
      sott: environment.loginradiusSott,
    });

    // Initialize login interface
    loginRadius.init('auth', {
      container: 'auth-container',
      onSuccess: (response: unknown) => {
        console.log('Login response:', response);
      },
      onError: (error: { error?: string; errorCode?: number }) => {
        console.error('Login error:', error);
      },
    });
  }
}
